<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "metaedit"
 *
 * Auto generated by Extension Builder 2016-10-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'metaedit',
	'description' => '',
	'category' => 'be',
	'author' => 'Samuel Weiss',
	'author_email' => 'samuel@whitenote.ch',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.00001',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.4.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);